platform :ios, '13.0'
#source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'Example' do

  pod 'SwiftMesh', :path => '../'
  pod 'ProgressHUD'
  pod 'SwiftBrick'
  pod 'SnapKit'
end
